# Generated by Django 4.2.3 on 2023-08-30 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nomenclatura', models.CharField(max_length=50)),
                ('nominales', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
            ],
            options={
                'verbose_name': 'Acción',
                'verbose_name_plural': 'Acciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Bonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nomenclatura', models.CharField(max_length=50)),
                ('nominales', models.IntegerField()),
                ('ultimo_valor', models.DecimalField(decimal_places=2, max_digits=50)),
                ('fecha_actualizacion', models.DateField()),
            ],
            options={
                'verbose_name': 'Bono',
                'verbose_name_plural': 'Bonos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cauciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nomenclatura', models.CharField(max_length=50)),
                ('nominales', models.IntegerField()),
                ('ultimo_valor', models.IntegerField()),
                ('fecha_actualizacion', models.DateField()),
            ],
            options={
                'verbose_name': 'Caución',
                'verbose_name_plural': 'Cauciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cedears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nomenclatura', models.CharField(max_length=50)),
                ('nominales', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
            ],
            options={
                'verbose_name': 'Cedear',
                'verbose_name_plural': 'Cedears',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Fci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nomenclatura', models.CharField(max_length=50)),
                ('cuotapartes', models.IntegerField()),
                ('ultimo_valor', models.DecimalField(decimal_places=2, max_digits=50)),
                ('fecha_actualizacion', models.DateField()),
            ],
            options={
                'verbose_name': 'Fondo Común',
                'verbose_name_plural': 'Fondos Comunes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
