# Generated by Django 4.2.3 on 2023-08-30 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cedears',
        ),
    ]
