# Generated by Django 4.2.3 on 2023-08-30 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_delete_cedears'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bonos',
            new_name='Bono',
        ),
    ]
