# Generated by Django 4.2.3 on 2023-08-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_rename_bonos_bono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bono',
            name='ultimo_valor',
            field=models.IntegerField(),
        ),
    ]
