# Generated by Django 4.2.3 on 2023-08-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_bono_ultimo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bono',
            name='ultimo_valor',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
