# Generated by Django 4.2.3 on 2023-09-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_bono_ultimo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='cauciones',
            name='ultimo_valor',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
